kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: lawrences-tech
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  # Port 8080 for frontend
  - containerPort: 80
    hostPort: 8080
    protocol: TCP
  # Port 5050 for backend
  - containerPort: 5050
    hostPort: 5050
    protocol: TCP
  # Port 443 for HTTPS (future use)
  - containerPort: 443
    hostPort: 443
    protocol: TCP
