apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lawrences-tech

resources:
  - namespace.yaml
  - configmap.yaml
  - server.yaml
  - client.yaml
  - ingress.yaml

secretGenerator:
  - name: app-secrets
    envs:
      - .env
    options:
      disableNameSuffixHash: true

generatorOptions:
  disableNameSuffixHash: true