apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: lawrences-tech
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: lawrences-tech-server:latest
        ports:
        - containerPort: 5050
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PORT
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: HOST
        - name: CLIENT_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: CLIENT_URL
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NODE_ENV
        - name: GOOGLE_OAUTH_CALLBACK_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: GOOGLE_OAUTH_CALLBACK_URL
        - name: GITHUB_OAUTH_CALLBACK_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: GITHUB_OAUTH_CALLBACK_URL
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGO_URL
        - name: GOOGLE_OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: GOOGLE_OAUTH_CLIENT_ID
        - name: GOOGLE_OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: GOOGLE_OAUTH_CLIENT_SECRET
        - name: GITHUB_OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: GITHUB_OAUTH_CLIENT_ID
        - name: GITHUB_OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: GITHUB_OAUTH_CLIENT_SECRET
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SESSION_SECRET
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5050
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5050
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: lawrences-tech
spec:
  selector:
    app: server
  ports:
  - protocol: TCP
    port: 5050
    targetPort: 5050
  type: ClusterIP
