

const Actions = {
    DISPLAY_ALERT: 'SHOW_ALERT',
    CLEAR_ALERT: 'CLEAR_ALERT',
    REGISTER_USER_BEGIN: 'REGISTER_USER_BEGIN',
    REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
    REGISTER_USER_ERROR: 'REGISTER_USER_ERROR',
    LOGIN_USER_BEGIN: 'LOGIN_USER_BEGIN',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_USER_ERROR: 'LOGIN_USER_ERROR',
    LOGOUT_USER: 'LOGOUT_USER',
}

Object.freeze(Actions);

export default Actions;